name: referencing
description: Library for working with coordinate reference systems.
version: 0.0.1
author: Rik Bellens <rik.bellens@appsup.be>
homepage: https://github.com/appsup-dart/referencing

environment:
  sdk: '>=1.21.0 <2.0.0'

dependencies:
  meta: '>=1.0.4 <2.0.0'
  vector_math: '>=2.0.3 <3.0.0'
  measure: '>=0.0.1 <0.1.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
